### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Satota2048** [Satota2048/protospace-34998#1]
#URL
https://protospace-34998.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@Satota2048 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]

- [ ] **プロトタイプ一覧ページにて、プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者の名前の、4つの情報について表示するようにしましょう**
 現状、投稿者の名前が表示されていません

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
 現状、コメントを投稿したユーザー名をクリックしてもユーザー詳細ページに飛びません

https://user-images.githubusercontent.com/59544869/113646951-d36fad80-96c4-11eb-801a-ae35edcffb78.mov



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@Satota2048 さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
